name = "sing-box-converter"
main = "work.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "subscribe.db"
database_id = ""
migrations_dir = "./drizzle/migrations"

[[rules]]
type = "Text"
handlers = ["*.html"]
globs = ["**/*.html"]